name: quiz_master
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  firebase_core: ^2.32.0
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.6.5
  flutter_local_notifications: ^19.0.0
  permission_handler: ^11.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
